const express=require("express")
const router=express.Router()
const userController=require('../controllers/user.controller')
const messageController=require('../controllers/message.controller')
router.get('/',userController.landingPages)
router.post('/signup',userController.signUp)
router.post('/login',userController.logIn)
router.post('/forgetPassword',userController.forgetEmail)
router.post('/resetPassword',userController.resetPassword)
router.get('/presentUser',userController.allInfo)
router.get('/allUsers',userController.getAllUser)
router.post('/allmessages',messageController.sendMessage)
router.get('/messages',messageController.allMessages)
router.post('/update',userController.uploadProfile)
router.post('/follow',userController.follow)
router.post('/like',userController.like)
router.post('/comment',userController.comment)
router.get('/postImage',userController.getPost)
router.post('/postImage',userController.savePost)
module.exports=router